lize)]
struct EctArgs {
    num_heights: i64,
    num_directions: i64,
}

#[polars_expr(output_type_func=struct_use_verts)]
pub fn ect(inputs: &[Series], kwargs: EctArgs) -> PolarsResult<Series> {
    let device = best_device();
    println!("Using device: {:?}", device);

    let mut ep_per_dim: HashMap<i64, ECTParams> = HashMap::new();

    let fields = &inputs[0].struct_()?.fields_as_series();
    let vdtype = fields[0].dtype().leaf_dtype();
    let kind: tch::Kind = match vdtype {
        DataType::Float32 => tch::Kind::Float,
        DataType::Float64 => tch::Kind::Double,
        _ => polars_bail!(InvalidOperation: format!(
            "vertex dtype {vdtype} not supported for ect"
        )),
    };

    iter_complex!(&inputs[0], |complex| {
        complex.interpolate_missing_down();
        let embedded_dimension = complex.get_vertices().shape()[1] as i64;

        if !ep_per_dim.contains_key(&embedded_dimension) {
            ep_per_dim.insert(
                embedded_dimension,
                ECTParams::new(
                    embedded_dimension,
                    kwargs.num_directions,
                    kwargs.num_heights,
                    device,
                    kind,
                ),
            );
        }

        let ep = ep_per_dim.get(&embedded_dimension).unwrap();
        let tensor_complex = TensorComplex::from(&complex, device);
        let ect: tch::Tensor = tensor_complex.ect(ep);
        tensor_to_flat(&ect, kind)
    })
}
