name: Test Cross-Platform Builds

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    name: Build and Test on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Install dependencies
        run: |
          pip install torch maturin pytest

      - name: Build package with maturin (using PyTorch lib)
        env:
          LIBTORCH_USE_PYTORCH: 1
        run: |
          maturin develop --release

      - name: Run tests
        run: pytest

