name: Cross-platform install & test (from repo)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly

      - name: Install maturin
        run: pip install maturin pytest

      - name: Build and install the package
        run: |
          maturin build --release
          pip install dist/*.whl

      - name: Verify installation
        run: python -c "import tdataframe; print('TDataFrame version:', tdataframe.__version__)"

      - name: Run tests
        run: pytest -v

